spring.config.import=optional:file:.env[.properties]
spring.application.name=clima_api_java
openweather.api.key=${OPENWEATHER_API_KEY}
openweather.api.url=${OPENWEATHER_API_URL}
server.port=${SERVER_PORT}
